name: release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

env:
  DOTNETVERSION: "8.0.x"
  APP: "I8Beef.Denon"
  SOLUTION: "./src/I8Beef.Denon.sln"
  BUILDOUTPUTPATH: "./src/I8Beef.Denon/bin/Release/netstandard2.0"
  PACKOUTPUTPATH: "./out"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET SDK ${{ env.DOTNETVERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNETVERSION }}

      - name: Set version
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Install dependencies
        run: dotnet restore ${{ env.SOLUTION }}

      - name: Build
        run: dotnet build ${{ env.SOLUTION }} --configuration Release --no-restore /p:Version=${{ env.VERSION }}

      - name: Test
        run: dotnet test ${{ env.SOLUTION }} --no-restore --verbosity normal --logger trx --results-directory "TestResults"

      - name: ZIP release artifact
        run: zip -r ${{ env.APP }}-${{ env.VERSION }}.zip ${{ env.BUILDOUTPUTPATH }}

      - name: GitHub release
        run: |
          gh release create "${{ github.ref_name }}" \
            "${{ env.APP }}-${{ env.VERSION }}.zip" \
            --title "${{ env.VERSION }}" \
            --generate-notes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: NuGet pack
        run: dotnet pack ${{ env.SOLUTION }} --configuration Release --no-restore --include-symbols /p:Version=${{ env.VERSION }} -o ${{ env.PACKOUTPUTPATH }}

      - name: Upload NuGet build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP }} NuGet Packages
          path: ${{ env.PACKOUTPUTPATH }}

      - name: NuGet push
        run: dotnet nuget push "./${{ env.PACKOUTPUTPATH }}/*.nupkg" --skip-duplicate --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_TOKEN }}